FROM golang:1.15 as golang
COPY go.mod go.sum* /src/
RUN set -x && \
  cd /src && \
  go mod download
ADD main.go /src/main.go
RUN set -x && \
    cd /src && \
    CGO_ENABLED=0 GOOS=linux go build -a -v -o goapp

FROM alpine
RUN apk add --no-cache ca-certificates

COPY --chown=nobody:nobody --from=golang /src/goapp /app/goapp

WORKDIR /app

USER nobody:nobody

CMD ["/app/goapp"]
